id: P010452
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W3CN6326
  title: རོ་སྒྲུང་།
  author: ''
  volumes:
    e5f2c5dd312c4d6e8253ef79c65fdab9:
      image_group_id: I3CN6328
      title: ''
      volume_number: 1
      total_pages: 308
      base_file: v001.txt
