id: IA6A27DF4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T14:39:17+00:00'
last_modified: '2022-06-08T13:42:42.267811+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN6326
  title: རོ་སྒྲུང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedTemporarily
  restrictedInChina: false
  base:
    8EE1:
      image_group_id: I3CN6328
      title: ''
      total_pages: 308
      order: 1
      base_file: 8EE1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
